# Generated by Django 4.2.30 on 2026-09-20 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=150, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("exfoliant", "Exfoliant"),
                            ("retinoid", "Retinoid"),
                            ("antioxidant", "Antioxidant"),
                            ("humectant", "Humectant"),
                            ("lipid", "Lipid / Barrier Support"),
                            ("peptide", "Peptide"),
                            ("sunscreen_filter", "Sunscreen Filter"),
                            ("soothing", "Soothing / Calming"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("brand", models.CharField(default="Joyory", max_length=150)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cleanser", "Cleanser"),
                            ("toner", "Toner"),
                            ("serum", "Serum"),
                            ("moisturizer", "Moisturizer"),
                            ("exfoliant", "Exfoliant"),
                            ("sunscreen", "Sunscreen"),
                            ("treatment", "Treatment"),
                        ],
                        max_length=50,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True)),
                (
                    "texture",
                    models.CharField(
                        choices=[
                            ("gel", "Gel / Water Gel"),
                            ("lightweight_lotion", "Lightweight Lotion / Fluid"),
                            ("rich_cream", "Rich Cream / Balm"),
                            ("oil", "Oil"),
                            ("foam", "Foam"),
                            ("liquid", "Liquid"),
                        ],
                        default="lightweight_lotion",
                        max_length=50,
                    ),
                ),
                (
                    "suitable_climate",
                    models.CharField(
                        choices=[
                            ("all", "All Climates"),
                            ("hot_humid", "Hot & Humid"),
                            ("hot_dry", "Hot & Dry"),
                            ("cold_dry", "Cold & Dry"),
                        ],
                        default="all",
                        max_length=50,
                    ),
                ),
                (
                    "hydration_level",
                    models.CharField(
                        choices=[
                            ("light", "Light Hydration"),
                            ("moderate", "Moderate Hydration"),
                            ("deep", "Deep Barrier Repair"),
                        ],
                        default="moderate",
                        max_length=50,
                    ),
                ),
                (
                    "active_level",
                    models.CharField(
                        choices=[
                            ("low", "Low / Gentle"),
                            ("medium", "Medium"),
                            ("high", "High / Concentrated Active"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("usage_frequency", models.CharField(default="daily", max_length=50)),
                (
                    "time_of_day",
                    models.CharField(
                        choices=[
                            ("morning", "Morning"),
                            ("evening", "Evening"),
                            ("both", "Both Morning & Evening"),
                        ],
                        default="both",
                        max_length=20,
                    ),
                ),
                (
                    "typical_duration_days",
                    models.IntegerField(
                        default=60, help_text="Average lifespan of bottle in days"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ingredients",
                    models.ManyToManyField(
                        blank=True, related_name="products", to="products.ingredient"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IngredientInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("caution", "Caution"),
                            ("warning", "Warning"),
                        ],
                        default="caution",
                        max_length=20,
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("irritation_risk", "Irritation Risk"),
                            ("barrier_stress", "Barrier Stress"),
                            ("ph_dependency", "pH Sensitivity / Dependency"),
                            ("reduced_efficacy", "Reduced Efficacy"),
                            ("compatible_synergy", "Compatible Synergy"),
                            ("sun_sensitivity", "Sun Sensitivity"),
                        ],
                        default="irritation_risk",
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "recommendation",
                    models.TextField(help_text="Suggested shopping/usage guidance"),
                ),
                (
                    "ingredient_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions_as_a",
                        to="products.ingredient",
                    ),
                ),
                (
                    "ingredient_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions_as_b",
                        to="products.ingredient",
                    ),
                ),
            ],
            options={
                "unique_together": {("ingredient_a", "ingredient_b")},
            },
        ),
    ]
