# Generated by Django 4.2.30 on 2026-09-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="concerns",
            field=models.CharField(
                default="Barrier Support, Daily Health",
                help_text="e.g. Fine Lines, Dark Spots, Acne, Redness",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="routine_stage",
            field=models.IntegerField(
                choices=[
                    (1, "Stage 1: Barrier Foundation"),
                    (2, "Stage 2: Targeted Prep & Hydration"),
                    (3, "Stage 3: Concentrated Active Integration"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="skin_types",
            field=models.CharField(
                default="All Skin Types",
                help_text="e.g. Sensitive, Oily, Dry, Combination",
                max_length=255,
            ),
        ),
    ]
