# Generated by Django 4.2.30 on 2026-09-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_concerns_product_routine_stage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Product image path or URL",
                max_length=500,
            ),
        ),
    ]
