# Generated by Django 4.2.30 on 2026-09-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="routine",
            name="auto_reorder_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="routine",
            name="auto_reorder_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Automatically schedule replenishment reorder upon routine completion",
            ),
        ),
        migrations.AddField(
            model_name="routine",
            name="auto_reorder_order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="routine",
            name="auto_reordered",
            field=models.BooleanField(
                default=False, help_text="True if automated reorder was dispatched"
            ),
        ),
        migrations.AddField(
            model_name="routinedeliveryitem",
            name="status",
            field=models.CharField(default="scheduled", max_length=50),
        ),
        migrations.AddField(
            model_name="routinedeliveryitem",
            name="tracking_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
