# Generated by Django 4.2.30 on 2026-09-20 14:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0002_routine_auto_reorder_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySkinFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                (
                    "skin_feel",
                    models.CharField(
                        choices=[
                            ("comfortable", "Comfortable"),
                            ("dry", "A little dry"),
                            ("irritated", "Irritated"),
                        ],
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "routine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skin_feedbacks",
                        to="routines.routine",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "unique_together": {("routine", "date")},
            },
        ),
    ]
