# Generated by Django 4.2.30 on 2026-09-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0003_dailyskinfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="routineprogress",
            name="session",
            field=models.CharField(default="all", max_length=20),
        ),
        migrations.AddField(
            model_name="routinestep",
            name="evening_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="routinestep",
            name="morning_completed",
            field=models.BooleanField(default=False),
        ),
    ]
